CP2K - A100
eth-cscs/alps-spack-stacks pull request #36
Opened 2023-08-17 20:08 UTC by RMeli

Requires/contains #35.

2023-08-18 07:27 UTC, RMeli commented
cscs-ci run cp2k

2023-08-18 08:39 UTC, RMeli commented
cscs-ci run cp2k

2023-08-18 09:14 UTC, RMeli commented
cscs-ci run cp2k

2023-08-18 09:25 UTC, RMeli commented
cscs-ci run cp2k

2023-09-04 06:38 UTC, RMeli commented
cscs-ci run cp2k

2023-09-04 08:36 UTC, bcumming requested changes
Looking good!

I have a few suggestions, and one major suggestion: provide some documentation in the `/docs` path.
See `mkdocs.yaml` in the project root.

2023-09-04 08:36 UTC, bcumming commented on recipes/cp2k/a100/environments.yaml
> +    scalapack:
Should we call this view `cp2k-scalapack`? From the user's perspective, that is what the environment contains.
The same goes for the ELPA version below.

2023-09-04 08:36 UTC, bcumming commented on recipes/cp2k/a100/environments.yaml
> +  - py-numpy
Should we make a `tools` view?

2023-09-04 08:36 UTC, bcumming commented on recipes/cp2k/a100/modules.yaml
> +        sirius+elpa: 'sirius+elpa/{version}'
:+1:

2023-09-04 08:36 UTC, bcumming commented on stack-build
> +    echo "usage: stack-build -n name -r recipe-path -s system -b build-root [-d]"
remove all of these `develop` changes, as they were merged in #32

2023-09-04 09:57 UTC, RMeli commented
cscs-ci run cp2k

2023-09-04 10:14 UTC, RMeli commented
cscs-ci run cp2k

2023-09-04 11:20 UTC, RMeli commented on docs/uenv-cp2k.md
> +To build your version of QE do the following steps:
```suggestion
To build your version of CP2K do the following steps:
```

2023-09-04 11:43 UTC, RMeli reviewed
Pin version of CP2K to `2023.2` and DBCSR to `2.6.0`.

`cuda_arch=70` for DBCSR is no longer required since https://github.com/spack/spack/pull/38939.

2023-09-04 11:43 UTC, RMeli commented on recipes/cp2k/a100/environments.yaml
> +  - cp2k@master +libxc +libint +spglib +cosma +sirius ~elpa build_system=cmake ^intel-oneapi-mkl ^cray-mpich
```suggestion
  - cp2k@2023.2 +libxc +libint +spglib +cosma +sirius ~elpa build_system=cmake ^intel-oneapi-mkl ^cray-mpich
```

2023-09-04 11:43 UTC, RMeli commented on recipes/cp2k/a100/environments.yaml
> +  - dbcsr@develop +cuda cuda_arch=70 +shared +openmp ^intel-oneapi-mkl ^cray-mpich
```suggestion
  - dbcsr@2.6.0 +cuda +shared +openmp ^intel-oneapi-mkl ^cray-mpich
```

2023-09-04 11:43 UTC, RMeli commented on recipes/cp2k/a100/environments.yaml
> +  - dbcsr@develop +cuda cuda_arch=70 +shared +openmp ^intel-oneapi-mkl ^cray-mpich
```suggestion
  - dbcsr@2.6.0 +cuda +shared +openmp ^intel-oneapi-mkl ^cray-mpich
```

2023-09-04 11:43 UTC, RMeli commented on recipes/cp2k/a100/environments.yaml
> +  - cp2k@master +libxc +libint +spglib +cosma +sirius +elpa build_system=cmake ^intel-oneapi-mkl ^cray-mpich
```suggestion
  - cp2k@2023.2 +libxc +libint +spglib +cosma +sirius +elpa build_system=cmake ^intel-oneapi-mkl ^cray-mpich
```

2023-09-04 15:26 UTC, RMeli commented
Waiting for https://github.com/spack/spack/pull/39782.

2023-09-07 19:33 UTC, RMeli commented
cscs-ci run cp2k

2023-09-08 07:47 UTC, bcumming approved these changes

2023-09-08 07:47 UTC, merged